### ISSUE TITLE
init方法的疑问

### ISSUE THREAD

**Issue by nierChen** [pgkk/kkpager#8]
init方法中，对于_config初始化，首先判断了_config是否为空，为什么这么做呢？
既然是初始化，或许直接强制赋值更好，不需要判断是否为空。

**Comment by chenchengbest** [comment]
确实存在一定的问题，ini中的_config 为空判断在异步多次重新加载分页插件的时候，存在config没更新的问题，我在项目中是直接去除的。 
Indeed there are some problems,  when using ajax to load data ,the _config is not null,so the kkpager.config is not int. I was directly removed in the project.
